version: "3.9"
services:
  application:
    build: .
    container_name: web-application
    ports:
      - 8080:8080
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_post=5672
      - spring_rabbitmq_username=admin
      - spring_rabbitmq_password=admin
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin