version: "3.9"
services:
  application:
    build: ./
    restart: always
    image: 11-application
    container_name: 11-application
    volumes:
      - ./build/libs/application-0.0.1-SNAPSHOT.jar:/app.jar
    ports:
      - 8080:8080
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_post=5672
      - spring_rabbitmq_username=admin
      - spring_rabbitmq_password=admin
    networks:
      - mynetwork
    depends_on:
      - rabbitmq
      - db

  trendingtopics:
    build: ./
    restart: always
    image: trendingtopics
    container_name: trendingtopics
    volumes:
      - /home/franferraz/Máster/TMDAD/TMDAD-multi-module/trendingtopics/build/libs/trendingtopics-0.0.1-SNAPSHOT.jar:/app.jar
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_post=5672
      - spring_rabbitmq_username=admin
      - spring_rabbitmq_password=admin
    networks:
      - mynetwork
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: user
    networks:
      - mynetwork
  db:
    image: 'postgres'
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge