version: "3.9"
services:
  application:
    build: ./
    restart: always
    image: 11-application
    container_name: 11-application
    ports:
      - 8080:8080
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_post=5672
      - spring_rabbitmq_username=admin
      - spring_rabbitmq_password=admin
    depends_on:
      - rabbitmq
      - db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  db:
    image: 'postgres'
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db